language: cpp

dist: trusty

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd MacMSRDriver && make kext library && cd ..; fi
  - mkdir build
  - cd build
  - cmake .. -LH
  - make

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

